Completed Lesson5.
Exp110rer/geekshop-server pull request #5
Opened 2021-08-29 21:21 UTC by Exp110rer

2021-08-30 08:30 UTC, Vokler requested changes

2021-08-30 08:30 UTC, Vokler commented on baskets/views.py
> +def totals(user):
Для таких функций, если вы решаете вынести их за пределы контроллера, лучше хранить в отдельном файле, например, в `utils.py`. То есть в папке `baskets` создать этот файл. Потому что во `views.py` должны быть в основном только контроллеры

2021-08-30 08:30 UTC, Vokler commented on baskets/views.py
> +    for basket in Basket.objects.filter(user=user):
Так же у вас переменная baskets уже высчитывается в контроллере `profile()`, так что в это ф-цию лучше передавать не пользователя, а сам список из корзин

2021-08-30 12:45 UTC, Exp110rer commented
Изменения внес. Надеюсь все сделал правильно :-)

2021-08-31 15:09 UTC, Vokler approved these changes

2021-08-31 15:09 UTC, merged